### ISSUE TITLE
Can't install on Mac OS X 10.10

### ISSUE THREAD

**Issue by jonaslejon** [tmetsch/python-dtrace#3]
Version info and build log below:

```
$ uname -a
Darwin mbp.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

$ sudo python setup.py install
running install
running build
running build_py
creating build
creating build/lib.macosx-10.10-intel-2.7
creating build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
copying dtrace_ctypes/__init__.py -> build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
copying dtrace_ctypes/consumer.py -> build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
copying dtrace_ctypes/dtrace_structs.py -> build/lib.macosx-10.10-intel-2.7/dtrace_ctypes
running build_ext
cythoning dtrace/dtrace.pyx to dtrace/dtrace.c

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, chew_func=None, chewrec_func=None, out_func=None,
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:239:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, chew_func=None, chewrec_func=None, out_func=None,
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:239:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:240:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 walk_func=None):
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:240:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:241:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:241:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:242:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. Gets a DTrace handle and sets some options.
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:242:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, script, chew_func=None, chewrec_func=None,
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:354:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, script, chew_func=None, chewrec_func=None,
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:354:49: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:355:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
                 out_func=None, walk_func=None):
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
                                                         ^
------------------------------------------------------------

dtrace/dtrace.pyx:355:58: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:356:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        '''
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
                                             ^
------------------------------------------------------------

dtrace/dtrace.pyx:356:46: Cannot convert 'object (object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:357:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        Constructor. will get the DTrace handle
        '''
        self.chew_func = chew_func or simple_chew
        self.chewrec_func = chewrec_func or simple_chewrec
        self.out_func = out_func or simple_out
        self.walk_func = walk_func or simple_walk
                                                ^
------------------------------------------------------------

dtrace/dtrace.pyx:357:49: Cannot convert 'object (object, object, object, object, int __pyx_skip_dispatch)' to Python object
building 'dtrace' extension
creating build/temp.macosx-10.10-intel-2.7
creating build/temp.macosx-10.10-intel-2.7/dtrace
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c dtrace/dtrace.c -o build/temp.macosx-10.10-intel-2.7/dtrace/dtrace.o
dtrace/dtrace.c:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: command 'cc' failed with exit status 1
```

**Comment by tmetsch** [comment]
Thanks for reporting this.

I will need to have a look at this. Sadly enough I don't have a Mac with that versions available atm. But let me try to figure sth out.

**Comment by tmetsch** [comment]
Can you test? I've pushed some code changes. Will look into the ctypes version now.

**Comment by arichardson** [comment]
Not sure about 10.10, but I got similar compile failures and with #10 merged it works on 10.15.

**Comment by tmetsch** [comment]
I think I'm going to close this issue - @arichardson: can you maybe quickly post the build output on Mac OS, so we have some trace that it works on 10.15? Sry to ask this - I do not have a Mac system handy :-(

**Comment by arichardson** [comment]
With #10 applied build output looks like this on macos 10.15:
```
running install
running build
running build_py
copying dtrace_ctypes/consumer.py -> build/lib.macosx-10.15-x86_64-3.9/dtrace_ctypes
copying dtrace_ctypes/dtrace_structs.py -> build/lib.macosx-10.15-x86_64-3.9/dtrace_ctypes
running build_ext
building 'dtrace' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I./dtrace_cython -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/Users/alex/cheri/python-dtrace/venv3/include -I/usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c dtrace_cython/consumer.c -o build/temp.macosx-10.15-x86_64-3.9/dtrace_cython/consumer.o
clang -bundle -undefined dynamic_lookup -L/usr/local/lib -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk build/temp.macosx-10.15-x86_64-3.9/dtrace_cython/consumer.o -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -ldtrace -o build/lib.macosx-10.15-x86_64-3.9/dtrace.cpython-39-darwin.so
running install_lib
copying build/lib.macosx-10.15-x86_64-3.9/dtrace.cpython-39-darwin.so -> /Users/alex/cheri/python-dtrace/venv3/lib/python3.9/site-packages
copying build/lib.macosx-10.15-x86_64-3.9/dtrace_ctypes/consumer.py -> /Users/alex/cheri/python-dtrace/venv3/lib/python3.9/site-packages/dtrace_ctypes
copying build/lib.macosx-10.15-x86_64-3.9/dtrace_ctypes/dtrace_structs.py -> /Users/alex/cheri/python-dtrace/venv3/lib/python3.9/site-packages/dtrace_ctypes
byte-compiling /Users/alex/cheri/python-dtrace/venv3/lib/python3.9/site-packages/dtrace_ctypes/consumer.py to consumer.cpython-39.pyc
byte-compiling /Users/alex/cheri/python-dtrace/venv3/lib/python3.9/site-packages/dtrace_ctypes/dtrace_structs.py to dtrace_structs.cpython-39.pyc
running install_egg_info
Writing /Users/alex/cheri/python-dtrace/venv3/lib/python3.9/site-packages/python_dtrace-0.0.11-py3.9.egg-info
```

**Comment by tmetsch** [comment]
Great, thanks!
